### ISSUE TITLE
Reproducing the Slam perfomance

### ISSUE THREAD

**Issue by Ashesham** [htkseason/VOLDOR#11]
Hi, thank you for sharing your work,
I have successfully build the full slam pipeline and was trying out the demo from the available data-set "TartanAir-oldtown". But while running with **mono**, I have found that I am unable to get a very good performance while activating the slam with "--enable_mapping --enable_loop_closure" (as seen below).

![image](https://user-images.githubusercontent.com/43771648/145943402-272beb6c-f974-435f-8b58-24862e76f106.png)

While checking the performance of Loop-closure with **stereo**, I was able to notice that it was not performing as well as shown in the demo while following the default parameters. 

![image](https://user-images.githubusercontent.com/43771648/145944166-7a5948fa-53f0-470c-9776-b57f9e07589a.png)

May I know if I am missing something?, Will be looking forward to your valuable input :)

**Comment by htkseason** [comment]
Hi Ashesham,

Thank you for the interest in our work and the feedbacks.

**1) For Oldtown-mono.**
I can see the camera poses do make sense, though they are not prefect due to the drift. 
You can press `x/z` key in the viewer to adjust visible depth range in order to pop up more structures. (See tips in README)
Please let me know if you get very different quantitative results than the one reported in the ICRA paper. 

**2) For the discrepencies with video.**
This is mostly because of the different hyper-parameters setup. For this published version, I increased the thresholds for the backend modules (i.e. loop-closure and mapping-links) for better robustness towards all kinds of dataset. This should not affect accuracy very much. Moreover, slower computers will also have less links.
You can reduce `mp_realtime_link_thresh`, `mp_link_consistency_thresh` for more local links, reduce `lc_bow_score_thresh`, `lc_geo_inlier_thresh` for more loop closures. (You can also see the sky is triangulated, where I masked them out in the video :)

Thank you again for the feedback. Feel free to let me know if you have further questions.

Best,
Min

**Comment by Ashesham** [comment]
Hi Min, 
Thank you for your quick response. The pointers on the hyper-parameters were helpful in reproducing similar performance! 

Best Regards!
Ash
