### ISSUE TITLE
How to mask invalid optical flow values?

### ISSUE THREAD

**Issue by s3r637** [htkseason/VOLDOR#6]
Hi @htkseason,

a very impressive job that you have done. A huge thank you for sharing the code!

I wonder if there is a way to mask optical flow values (mark as invalid/unknown)?

For example: "A flow value is considered "unknown" if either |u| or |v| is greater than 1e9." [see https://vision.middlebury.edu/flow/code/flow-code/README.txt]

However, the aim is for VOLDOR to ignore these pixels and not use them for optimization.
Is there such a possibility?

Kind regards
Sergej

**Comment by htkseason** [comment]
Hi Sergej,

Thank you for the question. It is a good suggestion to add an interface for masking known invalid optical flow pixels in the future. Since currently there is no such function, you may try set invalid pixels to float("nan"), zero or some random values (not sure if 'nan' will cause crush). 

However, if there is only a small amount of outliers, you do not need worry. Our framework is very robust to optical flow outliers. Idealy, they will be internally masked out if they are not congruent to the pose estimation, otherwise, they will not cause large error to the pose estimation.

The only ambigous case is when a large amount (>50%) of pixels congruent to a rigid motion of another moving object. In such case, if you know the mask of that moving object, you can try set them to zero/nan/random.

Best,
Min

**Comment by s3r637** [comment]
Hi Min,

thanks for answering me.

To mask a (engine) hood, I set the motion vectors to zero / nan / inf. Zeros worked best as far as I can tell. I haven't tried random values to be honest. I would have expected it to crash with nans and infs but oddly enough it didn't happen.

But to see if it works on my data at all, I just cut off the hood area.
I get the motion vectors ("optical flow") from an H.264 encoder / decoder chip. For the compression it is not relevant where the pixel blocks comes from, the main thing is that it looks identical and the decoded image looks reasonable.
 
When I calculate the optical flow with the suggested tool [PWC-Net](https://github.com/sniklaus/pytorch-pwc), the result looks much better. But my idea was to use VOLDOR with the motion vectors to avoid the step of pre-computing the optical flow.
There are several issues, e.g., the motion vectors always point to the previous image, so I have to convert it first, I lose a bit of accuracy as I have to round the values etc..

I close the issue because you answered my initial question. Thanks for that.

Best regards
Sergej
