### ISSUE TITLE
Real time? 

### ISSUE THREAD

**Issue by antithing** [htkseason/VOLDOR#7]
Hi! And thanks for making this code available.

Would it be possible to run this system in real time, from a live camera? 

What would the expected frame latency (fps) be? 

Thanks!

**Comment by htkseason** [comment]
Hi,

We currently do not have interfaces to live cameras. Since that requires interfacing with various third-party optical flow methods which will introduce large addtional dependencies that makes the project hard to use. Feel free to DIY the 'flow_loader' in `voldor_slam.py` to interface with any optical flow methods you like.

Our method generally runs around 15 fps on a GTX-1080Ti. The value may vary based on input size / hyper-parameters / hardware device. It is usually a good idea to decrease the input size for a faster runtime. While the real runtime should consider the optical flow estimator. For example, PWC-Net also runs like 15 fps. Some engineering works can be done to hide the latency.

Best,
Min
